# Generated by Django 5.2 on 2025-12-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_pedidoitem_codigo_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de rechazo por admin'),
        ),
    ]
